In [29]:
import pandas as pd

In [30]:
employee_data = pd.read_excel(
    'database/clean_DanhSachThongTinDoanVien.xlsx', dtype=str)

In [31]:
employee_data

,stt,maso_doanvien,hovaten,tinh,matinh,cmnd,huongluong_ngansach,huongluong_ngoaingansach,khongchuyentrach,chutich,...,vuvbkt,ngayvao_congdoan,Unnamed_19,Unnamed_20,Unnamed_21,Unnamed_22,nguyenquan_tinh,nguyenquan_matinh,gioitinh,ngaysinh
0,1,000005178473,Trần Văn Dần,Nam Định,14,020638174,NaN,NaN,NaN,NaN,...,NaN,01/01/2010,NaN,NaN,NaN,NaN,Bắc Giang,21,nam,10/01/1963
1,2,000005178402,Mai Phước Vinh,Quảng Nam,52,079080013078,NaN,NaN,NaN,NaN,...,NaN,01/02/2009,NaN,NaN,NaN,NaN,Lạng Sơn,22,nam,17/04/1980
2,3,000005178202,Trịnh Thái Xiêm,Tây Ninh,63,072080001551,NaN,NaN,NaN,NaN,...,NaN,05/04/2005,NaN,NaN,NaN,NaN,TP Hồ Chí Minh,23,nam,23/06/1980
3,4,000001491754,Đặng Phước Sang,An Giang,50,089094008005,NaN,NaN,NaN,NaN,...,NaN,21/08/2020,NaN,NaN,NaN,NaN,Nghệ An,24,nam,22/07/1994
4,5,000005178296,Võ Duy Khanh,Tây Ninh,63,079088016996,NaN,NaN,NaN,NaN,...,NaN,20/10/2012,NaN,NaN,NaN,NaN,Quảng Bình,25,nam,10/10/1988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,440,000006556838,Hà Thị Bích Hằng,Bình Định,64,215419368,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,10/04/1997
440,441,000006556839,Phạm Thị Vân Anh,Thái Bình,65,034191001750,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,03/11/1991
441,442,000006556837,Nguyễn Thị Lệ Quyên,Quảng Nam,52,049199003742,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,09/11/1999
442,443,000006556842,Phạm Mỹ Trinh Trinh,Sóc Trăng,59,365919385,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,23/11/1994
443,444,000006650148,Lê Thị Hồng Nhung,Nghệ An,24,040191040090,NaN,NaN,NaN,NaN,...,NaN,26/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,02/05/1991

In [32]:
len(employee_data)

444

In [33]:
import uuid
import random

In [34]:
list_users_id = ["EmployeeID_"+str(uuid.uuid4())
                 for i in range(len(employee_data))]
employee_data["employee_id"] = list_users_id

In [35]:
list_groups_id = ["GroupID_"+str(uuid.uuid4()) for i in range(5)]
user_group = [random.choice(list_groups_id) for i in range(len(employee_data))]
employee_data["group_id"] = user_group

In [36]:
# employee_data.to_excel("final_employee_data.xlsx", index=False)

# Load Final employee data

In [37]:
import pandas as pd
employee_data = pd.read_excel('database/final_employee_data.xlsx', dtype=str)

In [41]:
group_ids = employee_data["group_id"].unique().tolist()

In [44]:
group_names = [f"Trung Tâm {i + 1}" for i in range(len(group_ids))]

In [45]:
group_names

['Trung Tâm 1', 'Trung Tâm 2', 'Trung Tâm 3', 'Trung Tâm 4', 'Trung Tâm 5']

In [46]:
group_df = pd.DataFrame.from_dict(
    {"group_id": group_ids, "group_name": group_names})

In [48]:
group_df.to_excel("group_data.xlsx", index=False)

## Create temp data

In [ ]:
data = [
    {
        "key": "0",
        "Mã nhân viên": "...",
        "Tên": "adsf",
        "Vị trí": "ágd",
        "Số áo": "ádf"
    },
    {
        "key": "19031998-1",
        "Mã nhân viên": "àgds",
        "Tên": "3refd",
        "Vị trí": "c sadf",
        "Số áo": "fdgsdfg sdfgsdfg"
    }
]

In [2]:
import pandas as pd

In [3]:
employee_data = pd.read_excel('database/final_employee_data.xlsx', dtype=str)

In [4]:
employee_data

,stt,maso_doanvien,hovaten,tinh,matinh,cmnd,huongluong_ngansach,huongluong_ngoaingansach,khongchuyentrach,chutich,...,Unnamed_19,Unnamed_20,Unnamed_21,Unnamed_22,nguyenquan_tinh,nguyenquan_matinh,gioitinh,ngaysinh,employee_id,group_id
0,1,000005178473,Trần Văn Dần,Nam Định,14,020638174,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Bắc Giang,21,nam,10/01/1963,EmployeeID_9441341f-2140-401c-aac0-9e9ce088ca1a,GroupID_a330f381-4e38-4a93-a0c9-f194425aabf8
1,2,000005178402,Mai Phước Vinh,Quảng Nam,52,079080013078,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Lạng Sơn,22,nam,17/04/1980,EmployeeID_2f2a6700-cf47-42eb-927c-94e0022880eb,GroupID_990381bf-777a-4622-baba-0695fbf477dd
2,3,000005178202,Trịnh Thái Xiêm,Tây Ninh,63,072080001551,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,TP Hồ Chí Minh,23,nam,23/06/1980,EmployeeID_923bfaaa-bc49-4247-a0ea-69f5ea2fb49f,GroupID_f02b7648-cb29-43ec-9ea8-13e942b19de2
3,4,000001491754,Đặng Phước Sang,An Giang,50,089094008005,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Nghệ An,24,nam,22/07/1994,EmployeeID_3536b3da-b69d-4770-96df-d147ebad7cd6,GroupID_640cd15a-4df8-4937-a26b-e801d7ebdfa7
4,5,000005178296,Võ Duy Khanh,Tây Ninh,63,079088016996,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Quảng Bình,25,nam,10/10/1988,EmployeeID_c589fc7a-7a49-4832-ad6c-5ad53ea808b7,GroupID_f02b7648-cb29-43ec-9ea8-13e942b19de2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,440,000006556838,Hà Thị Bích Hằng,Bình Định,64,215419368,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nu,10/04/1997,EmployeeID_feab2e99-cf1f-4b71-8f35-b3f70b97bb99,GroupID_990381bf-777a-4622-baba-0695fbf477dd
440,441,000006556839,Phạm Thị Vân Anh,Thái Bình,65,034191001750,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nu,03/11/1991,EmployeeID_c63f7e85-6320-40e3-b1c6-87c0a0de535e,GroupID_640cd15a-4df8-4937-a26b-e801d7ebdfa7
441,442,000006556837,Nguyễn Thị Lệ Quyên,Quảng Nam,52,049199003742,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nu,09/11/1999,EmployeeID_1fd5b15a-4f35-4c02-9b73-c4891f52184d,GroupID_f02b7648-cb29-43ec-9ea8-13e942b19de2
442,443,000006556842,Phạm Mỹ Trinh Trinh,Sóc Trăng,59,365919385,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nu,23/11/1994,EmployeeID_09215c16-f807-46c1-8faa-03c6deed0d47,GroupID_9106a6c0-7ed2-488e-83db-149993c458ba
443,444,000006650148,Lê Thị Hồng Nhung,Nghệ An,24,040191040090,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nu,02/05/1991,EmployeeID_eda87e55-04a6-4ac4-89f3-679cd0502919,GroupID_990381bf-777a-4622-baba-0695fbf477dd

In [18]:
pos_lib = [
    "Tiền đạo",
    "Hậu vệ",
    "Thủ môn",
    "Tiền vệ",
    "Tiền vệ",
    "Tiền vệ",
    "Tiền vệ",
    "Trung vệ",
    "Trung phong",
    "Trung vệ phòng ngự"
]
numbers_lib = [str(i) for i in range(1, 30)]

In [8]:
import random
# temp_data = {
#         "key": "0",
#         "Mã nhân viên": "...",
#         "Tên": "adsf",
#         "Vị trí": "ágd",
#         "Số áo": "ádf"
#     },

# rand_point =

In [75]:
import uuid

total_data = []
cur_group_id = "GroupID_9106a6c0-7ed2-488e-83db-149993c458ba"
group_mems = employee_data[employee_data["group_id"] == cur_group_id]
for i in range(7):
        rand_idx = random.randint(0, len(group_mems) - 1)
        name = group_mems.iloc[rand_idx]["hovaten"]
        emp_id = group_mems.iloc[rand_idx]["maso_doanvien"]
        pos = random.choice(pos_lib)
        number = random.choice(numbers_lib)
        key = str(uuid.uuid4())
        cur_data = {
                "key": key,
                "Mã nhân viên": emp_id,
                "Tên": name,
                "Vị trí": pos,
                "Số áo": number
        }
        total_data.append(cur_data)

In [76]:
import json
json_total_data = json.dumps(total_data, ensure_ascii=False).replace("'", '"')
with open("test.json", "w", encoding="utf-8") as f:
        f.write(json_total_data)

### Marathon

In [ ]:
employee_data

In [85]:
import uuid

total_data = []
cur_group_id = "GroupID_f02b7648-cb29-43ec-9ea8-13e942b19de2"
group_mems = employee_data[employee_data["group_id"] == cur_group_id]
for i in range(30):
        rand_idx = random.randint(0, len(group_mems) - 1)
        name = group_mems.iloc[rand_idx]["hovaten"]
        emp_id = group_mems.iloc[rand_idx]["maso_doanvien"]
        gender = group_mems.iloc[rand_idx]["gioitinh"]
        gender = "Nam" if gender == "nam" else "Nữ"
        key = str(uuid.uuid4())
        cur_data = {
                "key": key,
                "Mã nhân viên": emp_id,
                "Tên": name,
                "giới tính": gender,
        }
        total_data.append(cur_data)

In [86]:
import json
json_total_data = json.dumps(total_data, ensure_ascii=False).replace("'", '"')
with open("test.json", "w", encoding="utf-8") as f:
        f.write(json_total_data)

### Múa

In [12]:
import uuid
import random
total_data = []
cur_group_id = "GroupID_9106a6c0-7ed2-488e-83db-149993c458ba"
group_mems = employee_data[employee_data["group_id"] == cur_group_id]
for i in range(2):
        rand_idx = random.randint(0, len(group_mems) - 1)
        name = group_mems.iloc[rand_idx]["hovaten"]
        emp_id = group_mems.iloc[rand_idx]["maso_doanvien"]
        # gender = group_mems.iloc[rand_idx]["gioitinh"]
        # gender = "Nam" if gender == "nam" else "Nữ"
        list_choices = ["Cháu lên ba", "Con cò bé bé", "Cháu yêu bà", "Ba thương con", "Chị ong nâu"]
        song = random.choice(list_choices)
        expect_time = random.choice([str(i) + " phút" for i in range(2, 10)])
        key = str(uuid.uuid4())
        cur_data = {
                "key": key,
                "Mã nhân viên": emp_id,
                "Tên": name,
                "Tiết mục": song,
                "Thời gian dự tính": expect_time,
        }
        total_data.append(cur_data)

In [13]:
import json
json_total_data = json.dumps(total_data, ensure_ascii=False).replace("'", '"')
with open("test.json", "w", encoding="utf-8") as f:
        f.write(json_total_data)