In [29]:
import pandas as pd

In [30]:
employee_data = pd.read_excel('database/clean_DanhSachThongTinDoanVien.xlsx', dtype=str)

In [31]:
employee_data

,stt,maso_doanvien,hovaten,tinh,matinh,cmnd,huongluong_ngansach,huongluong_ngoaingansach,khongchuyentrach,chutich,...,vuvbkt,ngayvao_congdoan,Unnamed_19,Unnamed_20,Unnamed_21,Unnamed_22,nguyenquan_tinh,nguyenquan_matinh,gioitinh,ngaysinh
0,1,000005178473,Trần Văn Dần,Nam Định,14,020638174,NaN,NaN,NaN,NaN,...,NaN,01/01/2010,NaN,NaN,NaN,NaN,Bắc Giang,21,nam,10/01/1963
1,2,000005178402,Mai Phước Vinh,Quảng Nam,52,079080013078,NaN,NaN,NaN,NaN,...,NaN,01/02/2009,NaN,NaN,NaN,NaN,Lạng Sơn,22,nam,17/04/1980
2,3,000005178202,Trịnh Thái Xiêm,Tây Ninh,63,072080001551,NaN,NaN,NaN,NaN,...,NaN,05/04/2005,NaN,NaN,NaN,NaN,TP Hồ Chí Minh,23,nam,23/06/1980
3,4,000001491754,Đặng Phước Sang,An Giang,50,089094008005,NaN,NaN,NaN,NaN,...,NaN,21/08/2020,NaN,NaN,NaN,NaN,Nghệ An,24,nam,22/07/1994
4,5,000005178296,Võ Duy Khanh,Tây Ninh,63,079088016996,NaN,NaN,NaN,NaN,...,NaN,20/10/2012,NaN,NaN,NaN,NaN,Quảng Bình,25,nam,10/10/1988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,440,000006556838,Hà Thị Bích Hằng,Bình Định,64,215419368,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,10/04/1997
440,441,000006556839,Phạm Thị Vân Anh,Thái Bình,65,034191001750,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,03/11/1991
441,442,000006556837,Nguyễn Thị Lệ Quyên,Quảng Nam,52,049199003742,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,09/11/1999
442,443,000006556842,Phạm Mỹ Trinh Trinh,Sóc Trăng,59,365919385,NaN,NaN,NaN,NaN,...,NaN,01/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,23/11/1994
443,444,000006650148,Lê Thị Hồng Nhung,Nghệ An,24,040191040090,NaN,NaN,NaN,NaN,...,NaN,26/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,nu,02/05/1991

In [32]:
len(employee_data)

444

In [33]:
import uuid
import random

In [34]:
list_users_id = ["EmployeeID_"+str(uuid.uuid4()) for i in range(len(employee_data))]
employee_data["employee_id"] = list_users_id

In [35]:
list_groups_id = ["GroupID_"+str(uuid.uuid4()) for i in range(5)]
user_group = [random.choice(list_groups_id) for i in range(len(employee_data))]
employee_data["group_id"] = user_group

In [36]:
# employee_data.to_excel("final_employee_data.xlsx", index=False)

# Load Final employee data

In [37]:
import pandas as pd
employee_data = pd.read_excel('database/final_employee_data.xlsx', dtype=str)

In [41]:
group_ids = employee_data["group_id"].unique().tolist()

In [44]:
group_names = [f"Trung Tâm {i + 1}" for i in range(len(group_ids))]

In [45]:
group_names

['Trung Tâm 1', 'Trung Tâm 2', 'Trung Tâm 3', 'Trung Tâm 4', 'Trung Tâm 5']

In [46]:
group_df = pd.DataFrame.from_dict({"group_id": group_ids, "group_name": group_names})

In [48]:
group_df.to_excel("group_data.xlsx", index=False)